#!/bin/bash

set -u

: ${LIBVIRT_DEFAULT_URI:=lxc:///}

LXC_BASE_DIR=/srv/lxc
LXC_BASE_FS=/dev/lxc/arch-base
LXC_MEMORY=512
LXC_FSSIZE=5g
LXC_NETWORK=network=default

prog=$(basename $0)

die () {
	echo "$prog: ERROR: $*" >&2
	exit 1
}

create_snapshot () {
	if ! lvs ${root_dev} > /dev/null 2>&1; then
		echo "Creating ${root_dev} from ${LXC_BASE_FS}."
		lvcreate -L $LXC_FSSIZE -n ${name}-root -s $LXC_BASE_FS
	else
		echo "Using existing ${root_dev}."
	fi
}

mount_snapshot () {
	echo "Mounting ${root_dev} on ${root_mount}."
	[ -d "${root_mount}" ] || mkdir ${root_mount}
	mount ${root_dev} ${root_mount}
}

create_container () {
	echo "Creating container ${name}."
	virt-install -n ${name} -r ${LXC_MEMORY} \
		-w ${LXC_NETWORK} \
		--filesystem ${root_mount},/ --print-xml |
	virsh define /dev/stdin
}

configure_container () {
	echo "Configuring ${name}."
	echo ${name} > ${root_mount}/etc/hostname
}

unmount_snapshot () {
	echo "Unmounting container filesystem."
	umount ${root_mount}
}

OPTS=$(
	getopt -o r:s:d:b:w: \
		--long lxc-dir:,base:,memory:,fssize:,network: \
		-n "${prog}" -- "$@"
	)

eval set -- "$OPTS"

while :; do
	case "$1" in
		-b|--base) LXC_BASE_FS="$2"; shift 2;;
		-d|--lxc-dir) LXC_BASE_DIR="$2"; shift 2;;
		-r|--memory) LXC_MEMORY=$2; shift 2;;
		-s|--fssize) LXC_FSSIZE=$2; shift 2;;
		-w|--network) LXC_NETWORK=$2; shift 2;;

		--) shift; break;;
	esac
done

name=$1
root_mount=${LXC_BASE_DIR}/${name}
root_dev=${LXC_BASE_FS%/*}/${name}-root

[ "$name" ] || die "you must specify a container name."
[ -d "$root_mount" ] && [ "$(ls -A ${root_mount})" ] &&
	die "directory ${root_mount} exists and is not empty."

set -e

create_snapshot
mount_snapshot
create_container
configure_container
unmount_snapshot

