#!/bin/bash

. /etc/lxc/lxc.conf

: ${LXC_DIR:=/lxc}
: ${LXC_BASE_FS:=${LXC_DIR}/FS}
: ${LXC_INSTANCE_DIR:=${LXC_DIR}/instance}
: ${LXC_DEVTAB:=/etc/lxc/devtab}

PATH=$PATH:$(dirname $0)

while getopts b: ch; do
	case $OPTARG in
	(b) LXC_BASE_FS=$OPTARG;;
	(d) LXC_DEVTAB=$OPTARG;;
	(n) NOCREATE=1;;
	esac
done
shift $(( $OPTIND - 1 ))

INSTANCE=$1
INSTANCE_DIR=${LXC_INSTANCE_DIR}/${INSTANCE}
INSTANCE_ROOT=${INSTANCE_DIR}/fs/root

if [ -d "${INSTANCE_DIR}" ]; then
	echo "ERROR: $INSTANCE_DIR already exists." >&2
	exit 1
fi

if [ ! -d "${LXC_BASE_FS}/etc" ]; then
	echo "ERROR: I don't believe $BASEFS is an OS root directory." >&2
	exit 1
fi

echo "Creating new instance $INSTANCE."
if ! mkdir -p ${INSTANCE_DIR}/fs/{root,var,tmp,dev}; then
	echo "ERROR: Failed to create instance directories." >&2
	exit 1
fi

echo "Copying /var."
if ! rsync -a ${LXC_BASE_FS}/var/ ${INSTANCE_DIR}/fs/var/; then
	echo "ERROR: Failed to copy /var." >&2
	exit 1
fi

echo "Creating lxc.conf."
cat > ${INSTANCE_DIR}/lxc.conf <<EOF
lxc.utsname = ${INSTANCE}
lxc.rootfs = ${INSTANCE_ROOT}
lxc.mount.entry = ${LXC_BASE_FS} ${INSTANCE_ROOT} none defaults,bind 0 0
lxc.mount.entry = ${INSTANCE_DIR}/fs/dev ${INSTANCE_ROOT}/dev none defaults,bind 0 0
lxc.mount.entry = ${INSTANCE_DIR}/fs/var ${INSTANCE_ROOT}/var none defaults,bind 0 0
lxc.mount.entry = ${INSTANCE_DIR}/fs/tmp ${INSTANCE_ROOT}/tmp none defaults,bind 0 0
lxc.mount = ${INSTANCE_DIR}/fstab
lxc.cap.drop = mknod

lxc.network.type = empty

lxc.tty = 4
lxc.pts = 1024

lxc.cgroup.devices.deny = a
EOF

echo "Creating devices."
lxc-dev-create ${LXC_DEVTAB} ${INSTANCE_DIR}/fs/dev
lxc-dev-perms >> ${INSTANCE_DIR}/lxc.conf

cat > ${INSTANCE_DIR}/fstab <<EOF
# Use this file for mounting additional filesystems
# in this container.
EOF

if [ "$NOCREATE" != 1 ]; then
	echo "Creating container."
	lxc-create -n ${INSTANCE} -f ${INSTANCE_DIR}/lxc.conf
fi

