#!/bin/bash

[ -f /etc/lxc/lxc.conf ] && . /etc/lxc/lxc.conf

: ${LXC_DIR:=/lxc}
: ${LXC_BASE_FS:=${LXC_DIR}/base}
: ${LXC_INSTANCE_DIR:=${LXC_DIR}/instance}
: ${LXC_DEVTAB:=/etc/lxc/devtab}
: ${LXC_NETWORK_LINK:=lxc0}

PATH=$PATH:$(dirname $0)

while getopts b:d:i:n ch; do
	case $ch in
	(b) LXC_BASE_FS=$OPTARG;;
	(d) LXC_DEVTAB=$OPTARG;;
	(n) NOCREATE=1;;
	(i) INSTANCE_IP=$OPTARG;;
	esac
done
shift $(( $OPTIND - 1 ))

INSTANCE=$1
INSTANCE_DIR=${LXC_INSTANCE_DIR}/${INSTANCE}
INSTANCE_ROOT=${INSTANCE_DIR}/fs/root
INSTANCE_CONF=${INSTANCE_DIR}/lxc.conf

if [ -d "${INSTANCE_DIR}" ]; then
	echo "ERROR: $INSTANCE_DIR already exists." >&2
	exit 1
fi

if [ ! -d "${LXC_BASE_FS}/etc" ]; then
	echo "ERROR: I don't believe $LXC_BASE_FS is an OS root directory." >&2
	exit 1
fi

echo "Creating new instance $INSTANCE."
if ! mkdir -p ${INSTANCE_DIR}/fs/{root,var,tmp,dev}; then
	echo "ERROR: Failed to create instance directories." >&2
	exit 1
fi

echo "Copying /var."
if ! rsync -a ${LXC_BASE_FS}/var/ ${INSTANCE_DIR}/fs/var/; then
	echo "ERROR: Failed to copy /var." >&2
	exit 1
fi

echo "Creating $INSTANCE_CONF."
cat > $INSTANCE_CONF <<EOF
lxc.utsname = ${INSTANCE}
lxc.rootfs = ${INSTANCE_ROOT}
lxc.mount.entry = ${LXC_BASE_FS} ${INSTANCE_ROOT} none defaults,bind 0 0
lxc.mount.entry = ${INSTANCE_DIR}/fs/dev ${INSTANCE_ROOT}/dev none defaults,bind 0 0
lxc.mount.entry = ${INSTANCE_DIR}/fs/var ${INSTANCE_ROOT}/var none defaults,bind 0 0
lxc.mount.entry = ${INSTANCE_DIR}/fs/tmp ${INSTANCE_ROOT}/tmp none defaults,bind 0 0
lxc.mount = ${INSTANCE_DIR}/fstab
lxc.cap.drop = mknod

lxc.tty = 4
lxc.pts = 1024

EOF

echo "Creating network configuration."
if ! [ "$INSTANCE_IP" ]; then
	cat >> $INSTANCE_CONF <<-EOF
	lxc.network.type = empty

	EOF
else
	cat >> $INSTANCE_CONF <<-EOF
	lxc.network.type = veth
	lxc.network.link = $LXC_NETWORK_LINK
	lxc.network.flags = up
	lxc.network.name = eth0
	lxc.network.ipv4 = $INSTANCE_IP

	EOF
fi


echo "Creating device configuration."
echo lxc.cgroup.devices.deny = a >> $INSTANCE_CONF
lxc-dev-create ${LXC_DEVTAB} ${INSTANCE_DIR}/fs/dev
lxc-dev-perms ${LXC_DEVTAB} >> ${INSTANCE_DIR}/lxc.conf

cat > ${INSTANCE_DIR}/fstab <<EOF
# Use this file for mounting additional filesystems
# in this container.
EOF

if [ "$NOCREATE" != 1 ]; then
	echo "Creating container."
	lxc-create -n ${INSTANCE} -f ${INSTANCE_DIR}/lxc.conf
fi

